"""Type stubs for the compiled replay engine (tickpipe.backtest._replay)."""

from typing import Any

TICK_RECORD_ITEMSIZE: int

class EventQueue:
    def push(self, timestamp_ns: int, sequence: int, rank: int) -> None: ...
    def pop(self) -> tuple[int, int, int]: ...
    def empty(self) -> bool: ...
    def __len__(self) -> int: ...

class Fill:
    order_id: int
    symbol_id: int
    side: int
    size_ticks: int
    tick_price_ticks: int
    fill_price_ticks: int
    slippage_ticks: int
    trade_ts_ns: int

class ReplayEngine:
    def __init__(
        self,
        speed: float = 0.0,
        tick_scale: int = 1000000000,
        order_entry_latency_ns: int = 0,
        slippage_fixed_ticks: int = 0,
        slippage_per_share_ticks: int = 0,
    ) -> None: ...
    def set_ticks(self, ticks: Any) -> None: ...
    def set_symbols(self, symbols: list[str]) -> None: ...
    def set_trade_ids(self, trade_ids: list[str]) -> None: ...
    def set_trade_callback(self, callback: Any) -> None: ...
    def set_book_delta_callback(self, callback: Any) -> None: ...
    def set_fill_callback(self, callback: Any) -> None: ...
    def submit_order(self, symbol_id: int, side: int, size_ticks: int) -> int: ...
    def pop_fills(self) -> list[Fill]: ...
    def current_ts_ns(self) -> int: ...
    def run(self) -> None: ...
